name: Deploy Kubernetes

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: aguinaldomneto/projeto-devops

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      VERSION: ${{ steps.version.outputs.VERSION }}

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Login Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Gerar versão
      id: version
      run: echo "VERSION=v1.0.${{ github.run_number }}" >> $GITHUB_OUTPUT

    - name: Build imagem
      run: |
        docker build -t $IMAGE_NAME:${{ steps.version.outputs.VERSION }} .

    - name: Push imagem
      run: |
        docker push $IMAGE_NAME:${{ steps.version.outputs.VERSION }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/k8s

          VERSION=${{ needs.build-and-push.outputs.VERSION }}

          echo "Deploy versão: $VERSION"

          # atualiza imagem no deployment
          kubectl set image deployment/devops-app \
          app=aguinaldomneto/projeto-devops:$VERSION

          # aguarda rollout
          kubectl rollout status deployment devops-app
