name: Deploy Multi Service Kubernetes

on:
  push:
    branches:
      - main

env:
  FRONT_IMAGE: aguinaldomneto/projeto-devops
  API_IMAGE: aguinaldomneto/projeto-api

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      VERSION: ${{ steps.version.outputs.VERSION }}

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Login Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Gerar versão
      id: version
      run: echo "VERSION=v1.0.${{ github.run_number }}" >> $GITHUB_OUTPUT

    # 🔥 FRONTEND
    - name: Build frontend
      run: |
        docker build -t $FRONT_IMAGE:${{ steps.version.outputs.VERSION }} .

    - name: Push frontend
      run: |
        docker push $FRONT_IMAGE:${{ steps.version.outputs.VERSION }}

    # 🔥 BACKEND (simulado agora)
    - name: Build API (simples)
      run: |
        docker pull hashicorp/http-echo
        docker tag hashicorp/http-echo $API_IMAGE:${{ steps.version.outputs.VERSION }}
        docker push $API_IMAGE:${{ steps.version.outputs.VERSION }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
          VERSION=${{ needs.build-and-push.outputs.VERSION }}

          echo "Deploy versão: $VERSION"

          # FRONTEND
          kubectl set image deployment/devops-app \
          app=aguinaldomneto/projeto-devops:$VERSION

          # BACKEND
          kubectl set image deployment/api-app \
          api=aguinaldomneto/projeto-api:$VERSION

          # acompanhar rollout
          kubectl rollout status deployment devops-app
          kubectl rollout status deployment api-app
